### ISSUE TITLE
The MNIST model seems corrupted

### ISSUE THREAD

**Issue by owulveryck** [onnx/models#103]
Hello,

I am trying to run the MNIST model on my [`go backend`](https://github.com/owulveryck/gorgonnx/issues/2) for days without success, so I wanted to run it step by step on caffe2 to see what I did wrong.

I have downloaded the docker image of onnx+caffe2 to test:

`docker run -it --rm onnx/onnx-docker:cpu`

Then I have downloaded the example:

`curl -s https://www.cntk.ai/OnnxModels/mnist/opset_7/mnist.tar.gz | tar xzf -`

then run this script:

```python
import numpy as np
import onnx
import os
import glob
import caffe2.python.onnx.backend as backend

from onnx import numpy_helper

model = onnx.load('model.onnx')
test_data_dir = 'test_data_set_0'

# Load inputs
inputs = []
inputs_num = len(glob.glob(os.path.join(test_data_dir, 'input_*.pb')))
for i in range(inputs_num):
    input_file = os.path.join(test_data_dir, 'input_{}.pb'.format(i))
    tensor = onnx.TensorProto()
    with open(input_file, 'rb') as f:
        tensor.ParseFromString(f.read())
    inputs.append(numpy_helper.to_array(tensor))

# Load reference outputs
ref_outputs = []
ref_outputs_num = len(glob.glob(os.path.join(test_data_dir, 'output_*.pb')))
for i in range(ref_outputs_num):
    output_file = os.path.join(test_data_dir, 'output_{}.pb'.format(i))
    tensor = onnx.TensorProto()
    with open(output_file, 'rb') as f:
        tensor.ParseFromString(f.read())
    ref_outputs.append(numpy_helper.to_array(tensor))

# Run the model on the backend
outputs = list(backend.run_model(model, inputs))

# Compare the results with reference outputs.
for ref_o, o in zip(ref_outputs, outputs):
    np.testing.assert_almost_equal(ref_o, o)
```

And it gives this result:
```
Traceback (most recent call last):
  File "onnx_caffe2.py", line 33, in <module>
    outputs = list(backend.run_model(model, inputs))
  File "/root/programs/onnx/onnx/backend/base.py", line 86, in run_model
    return backend.run(inputs)
  File "/root/programs/pytorch/caffe2/python/onnx/backend_rep.py", line 57, in run
    self.workspace.RunNet(self.predict_net.name)
  File "/root/programs/pytorch/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/root/programs/pytorch/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/root/programs/pytorch/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at reshape_op.h:110] total_size == size. 64 vs 256. Argument `shape` does not agree with the input data. (64 != 256)Error from operator:
input: "Pooling160_Output_0" input: "Pooling160_Output_0_reshape0_shape" output: "Pooling160_Output_0_reshape0" output: "OC2_DUMMY_1" name: "Times212_reshape0" type: "Reshape" device_option { device_type: 0 cuda_gpu_id: 0 }
```

Do I miss something? Maybe the MNIST model from CNTK has some specificities? Thank you for your help,

**Comment by blackrez** [comment]
Hello, I work with @owulveryck and I run the models with the following code :

```
import numpy as np
import onnx
import os
import glob
import onnxruntime.backend as backend 

from onnx import numpy_helper

model = onnx.load('model.onnx')
test_data_dir = 'test_data_set_0'

# Load inputs
inputs = []
inputs_num = len(glob.glob(os.path.join(test_data_dir, 'input_*.pb')))
for i in range(inputs_num):
    input_file = os.path.join(test_data_dir, 'input_{}.pb'.format(i))
    tensor = onnx.TensorProto()
    with open(input_file, 'rb') as f:
        tensor.ParseFromString(f.read())
    inputs.append(numpy_helper.to_array(tensor))

# Load reference outputs
ref_outputs = []
ref_outputs_num = len(glob.glob(os.path.join(test_data_dir, 'output_*.pb')))
for i in range(ref_outputs_num):
    output_file = os.path.join(test_data_dir, 'output_{}.pb'.format(i))
    tensor = onnx.TensorProto()
    with open(output_file, 'rb') as f:
        tensor.ParseFromString(f.read())
    ref_outputs.append(numpy_helper.to_array(tensor))

# Run the model on the backend
prep_model = backend.prepare(model)
outputs = list(prep_model.run(inputs))

# Compare the results with reference outputs.
for ref_o, o in zip(ref_outputs, outputs):
    np.testing.assert_almost_equal(ref_o, o)
```


And we got this results : 

```
AssertionError                            Traceback (most recent call last)
<ipython-input-21-6a1058f18619> in <module>
     37 # Compare the results with reference outputs.
     38 for ref_o, o in zip(ref_outputs, outputs):
---> 39     np.testing.assert_almost_equal(ref_o, o)
     40 

/usr/local/lib/python3.5/dist-packages/numpy/testing/_private/utils.py in assert_almost_equal(actual, desired, decimal, err_msg, verbose)
    566     if isinstance(actual, (ndarray, tuple, list)) \
    567             or isinstance(desired, (ndarray, tuple, list)):
--> 568         return assert_array_almost_equal(actual, desired, decimal, err_msg)
    569     try:
    570         # If one of desired/actual is not finite, handle it specially here:

/usr/local/lib/python3.5/dist-packages/numpy/testing/_private/utils.py in assert_array_almost_equal(x, y, decimal, err_msg, verbose)
    971     assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
    972              header=('Arrays are not almost equal to %d decimals' % decimal),
--> 973              precision=decimal)
    974 
    975 

/usr/local/lib/python3.5/dist-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    787                                 verbose=verbose, header=header,
    788                                 names=('x', 'y'), precision=precision)
--> 789             raise AssertionError(msg)
    790     except ValueError:
    791         import traceback

AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 70.0%)
 x: array([  975.6701  ,  -618.72394 ,  6574.5684  ,   668.02893 ,
        -917.27094 , -1671.6359  , -1952.7599  ,   -61.549873,
        -777.17664 , -1439.5316  ], dtype=float32)
 y: array([  975.67004 ,  -618.72406 ,  6574.566   ,   668.0283  ,
        -917.27094 , -1671.6353  , -1952.7599  ,   -61.549873,
        -777.1765  , -1439.5314  ], dtype=float32)
```

Can we consider the model is working ?

**Comment by mx-iao** [comment]
@blackrez, up to 3 decimal places is as expected

**Comment by owulveryck** [comment]
The bug was in hidden in the backend I am using (Gorgonia in Go) and has been fixed; I am closing this issue.

Thank you for your help.
