### ISSUE TITLE
Error on running Super Resolution Model from ONNX

### ISSUE THREAD

**Issue by nyanmn** [onnx/models#385]
Testing ONNX model for [super resolution model](https://github.com/onnx/models/tree/master/vision/super_resolution/sub_pixel_cnn_2016), I have error running [this sample program](https://github.com/onnx/models/blob/master/vision/super_resolution/sub_pixel_cnn_2016/dependencies/Run_Super_Resolution_Model.ipynb).

My ONNX version is 1.5.0 with onnxruntime 1.4.0. [Onnxruntime was installed using pip](https://pypi.org/project/onnxruntime/). Pytorch version is 1.6.0

Error is at 

`ort_session = onnxruntime.InferenceSession('/home/itc/pytorch/sub_pixel_cnn_2016/model/super-resolution-10.onnx')`

The error is in loading onnx model.

```
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    ort_session = onnxruntime.InferenceSession('/home/itc/pytorch/sub_pixel_cnn_2016/model/super-resolution-10.onnx')
  File "/home/itc/pytorch/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/home/itc/pytorch/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 166, in _load_model
    True)
RuntimeError: /onnxruntime_src/onnxruntime/core/session/inference_session.cc:238 onnxruntime::InferenceSession::InferenceSession(const onnxruntime::SessionOptions&, const onnxruntime::Environment&, const string&) status.IsOK() was false. Given model could not be parsed while creating inference session. Error message: Protobuf parsing failed.
```
 
How can I solve the error?

**Comment by kit1980** [comment]
Link to the StackOverflow question (duplicate of this issue) - https://stackoverflow.com/questions/64273951/error-on-running-super-resolution-model-from-onnx

**Comment by kit1980** [comment]
I believe this question was resolved on StackOverflow and this issue can be now closed.

**Comment by liuyangly1** [comment]
I get the same problem. I found the download model file sdd-10.onnx is 113 KB instead of  80.4 MB, so you should download the model file again.
