### ISSUE TITLE
KeyError: '475' mobilenet imagenet inference notebook

### ISSUE THREAD

**Issue by AK391** [onnx/models#502]
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    sym, arg_params, aux_params = import_model('mobilenetv2-7.onnx')
  File "/home/user/.local/lib/python3.8/site-packages/mxnet/contrib/onnx/onnx2mx/import_model.py", line 60, in import_model
    sym, arg_params, aux_params = graph.from_onnx(model_proto.graph, opset_version=model_opset_version)
  File "/home/user/.local/lib/python3.8/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 116, in from_onnx
    inputs = [self._nodes[i] for i in node.input]
  File "/home/user/.local/lib/python3.8/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 116, in <listcomp>
    inputs = [self._nodes[i] for i in node.input]
KeyError: '475'

**Comment by jcwchen** [comment]
Hi @AK391,
Thank you for catching it. I guess for the original version of the model, mobilenetv2-7.onnx might work. Could you please try this old [model](https://github.com/vinitra-zz/models/blob/7301ce1e16891ed5f75dd15a6a53a643001288f0/vision/classification/mobilenet/model/mobilenetv2-7.onnx) instead? There were several updates for mobilenetv2-7.onnx (for instance, https://github.com/onnx/models/pull/410) and something might not be supported by the mxnet-onnx yet. As you can see from [here](https://github.com/apache/incubator-mxnet/issues/19803), mxnet-onnx does not support it even for now. The notebook in onnx/models needs to be updated as well to prevent future confusion.

**Comment by zzxiang** [comment]
Thank you, @jcwchen . I encountered the same issue. The old model you specified worked!
