### ISSUE TITLE
ShuffleNet-v1 opset8 failed in C# test

### ISSUE THREAD

**Issue by mszhanyi** [onnx/models#559]
# Bug Report

### error message ###
```
Failed TestPreTrainedModels(opsetDir: "D:\\a\\_work\\1\\b\\models\\zoo\\opset8", modelName: "ShuffleNet-v1") [217 ms]
  Error Message:
   System.Exception : Opset opset8, Model ShuffleNet-v1: ModelFile = D:\a\_work\1\b\models\zoo\opset8\ShuffleNet-v1\model.onnx error = [ErrorCode:NotImplemented] Could not find an implementation for BatchNormalization(6) node with name ''
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeApiStatus.shared.cs:line 31
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.shared.cs:line 776
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.shared.cs:line 59
   at Microsoft.ML.OnnxRuntime.Tests.InferenceTest.TestPreTrainedModels(String opsetDir, String modelName) in D:\a\_work\1\s\csharp\test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\InferenceTest.netcore.cs:line 496
  Stack Trace:
     at Microsoft.ML.OnnxRuntime.Tests.InferenceTest.TestPreTrainedModels(String opsetDir, String modelName) in D:\a\_work\1\s\csharp\test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\InferenceTest.netcore.cs:line 615
```

looks opset7 and opset9 passed

**Comment by jcwchen** [comment]
Hi @mszhanyi,
Thanks for catching this. I take a look at the model and it seems that the opset_version is incorrect... The uploaded model files for `shufflenet-6.onnx` and `shufflenet-8.onnx` are reversed. To verify it, could you please use `shufflenet-6.onnx` for testing opset8 instead? If it passes, I will submit a PR to reverse them.

**Comment by mszhanyi** [comment]
@jcwchen 
Yes, it worked after swapping it
https://github.com/microsoft/onnxruntime/blob/7278d8b8d28460fd583aa6323d193d2cb960f320/tools/ci_build/github/azure-pipelines/templates/win-gpu-ci.yml#L193-L198
